### ISSUE TITLE
`x_farming:string` registered despite being set as an alias to `farming:string`

### ISSUE THREAD

**Issue by programmerjake** [asuna-mt/x_farming#1]
this makes the alias not work, which makes it impossible to craft `farming:string`. basically, the following section of code needs to be commented out or put in an `if farming-mod-not-detected` block.
https://github.com/asuna-mt/x_farming/blob/08ab00202fb8b549744becf7e9546bc533508949/craftitems.lua#L61-L66

**Comment by programmerjake** [comment]
there's a similar issue with not being able to craft wool directly from 4 cotton, though there is a way around that.

**Comment by EmptyStar** [comment]
You're right about the code that needs to change. I put the alias in the wrong spot when I tried to alias it before. I think I have a fix for it and also for wool.

My solution for wool will be to alias pillows to wool with the pillow groups added for crafting compatibility since it looks like pillows are mostly a carbon copy of wool with a couple minor differences. I've really been trying hard to cut down on node duplication in Everness and X Farming and I feel like aliases are the right answer in most cases.

**Comment by EmptyStar** [comment]
This is fixed in version v0.19.0. Feel free to reply/reopen if you still notice any issues.
